### ISSUE TITLE
Generate Crossplane controller with Upjet?

### ISSUE THREAD

**Issue by fabiand** [kubevirt/terraform-provider-kubevirt#48]
https://github.com/upbound/upjet

As described in https://github.com/crossplane/crossplane/issues/1975#issuecomment-1557917502 - Would it be easy to generate a baisc crossplane provider using this repository?

**Comment by nirarg** [comment]
Hi @fabiand ,
This repository can be used for generating crossplane provider.
But please note that this probably missing some features which should be added in order to give wider support.
If it needed and I can help on improving this provider, of course depends on priorities and capacity
@chenyosef FYI
