### ISSUE TITLE
Is this project dead?

### ISSUE THREAD

**Issue by evilhamsterman** [kubevirt/terraform-provider-kubevirt#81]
The providers has only had one release and no updates since then, there are many dependabot PRs that are sitting unmerged. Are there plans to work on this anymore?

**Comment by fabiand** [comment]
That's a fair ask.

As so often, open source projects depend on contributors.
@evilhamsterman if there is value for you, can you contribute?

@nirarg you were one of the more active contributors - what's the perspective for this project?

**Comment by evilhamsterman** [comment]
Sorry I don't really have Go skills or the time right now to contribute. The ability to deploy kubevirt resources can be managed with the Terraform Kubernetes manifests feature https://registry.terraform.io/providers/hashicorp/kubernetes/latest/docs/resources/manifest so this isn't strictly necessary. Though it would make autocomplete better for a nicer experience or having to run YAML manifests through a converter.

**Comment by nirarg** [comment]
Hi @evilhamsterman and @fabiand 

Apologies for the delayed response.

The repository has not been actively maintained lately, which means there is work to do in order to accommodate the latest Kubevirt API changes.
It's up to the Kubevirt team to determine how to incorporate this support, but I'm happy to help get things moving if needed.

Regarding the "kubernetes_manifest" resource in the Kubernetes provider, it can be used for managing Kubevirt resources, which could be a great solution if you can't wait for the Kubevirt provider to be ready.

**Comment by evilhamsterman** [comment]
kubernetes_manifest works but it can be annoying because working with CRDs and mutators is a pain. You have to go back and forth figuring out what fields terraform complains about to add to the computed_fields array https://registry.terraform.io/providers/hashicorp/kubernetes/latest/docs/resources/manifest#computed-fields. If this isn't going to receive any support the project should be closed
